import type { SourceMapEntry } from '../core/types'

export const sourceMap: SourceMapEntry[] = [
  {
    id: 'temas-examen',
    label: 'Temas de Examen.docx',
    path: 'Temas de Examen.docx',
    topics: ['alcance del examen', 'simplex', 'inventarios', 'pronósticos', 'redes'],
    priority: 'alta',
    reason: 'Es la fuente más directa para definir qué entra, qué no entra y cómo se reparte el examen entre práctica y teoría aplicada.',
  },
  {
    id: 'preguntas-teorico',
    label: 'Preguntas Teórico.docx',
    path: 'Preguntas Teórico.docx',
    topics: ['simplex', 'sensibilidad', 'inventarios', 'pronósticos', 'redes'],
    priority: 'alta',
    reason: 'Sirve para transformar teoría suelta en preguntas cortas pegadas a la resolución práctica.',
  },
  {
    id: 'notebooklm-guia',
    label: 'Material generado por NotebookLM/notebook-guia-estudio.md',
    path: 'Material generado por NotebookLM/notebook-guia-estudio.md',
    topics: ['síntesis transversal', 'glosario', 'apoyo conceptual'],
    priority: 'media',
    reason: 'Resume el corpus y ayuda a redactar feedback breve sin desplazar a las fuentes de examen.',
  },
  {
    id: 'formulacion-modelos',
    label: 'Material de estudio/1. Formulación de modelos.pdf',
    path: 'Material de estudio/1. Formulación de modelos.pdf',
    topics: ['programación lineal', 'modelado'],
    priority: 'media',
    reason: 'Respalda la lectura de restricciones y la formulación base de programación lineal.',
  },
  {
    id: 'dualidad-sensibilidad',
    label: 'Material de estudio/3. Dualidad y sensibilidad.pdf',
    path: 'Material de estudio/3. Dualidad y sensibilidad.pdf',
    topics: ['dualidad', 'precio sombra', 'cambio de VLD'],
    priority: 'alta',
    reason: 'Es la base matemática de la sala principal de simplex y sensibilidad.',
  },
  {
    id: 'inventarios-cep',
    label: 'Material de estudio/Modelos CEP y con Ruptura.pdf',
    path: 'Material de estudio/Modelos CEP y con Ruptura.pdf',
    topics: ['inventario sin ruptura', 'inventario con ruptura'],
    priority: 'alta',
    reason: 'Da el sustento para elegir el modelo correcto, calcular Q* y discutir pedidos pendientes.',
  },
  {
    id: 'inventarios-reab',
    label: 'Material de estudio/Modelos con Reab Unif y Discont.pdf',
    path: 'Material de estudio/Modelos con Reab Unif y Discont.pdf',
    topics: ['reabastecimiento uniforme'],
    priority: 'alta',
    reason: 'Respaldó la variante con producción/reaprovisionamiento gradual que aparece en examen.',
  },
  {
    id: 'pronosticos-pdf',
    label: 'Material de estudio/Modelos de Pronósticos.pdf',
    path: 'Material de estudio/Modelos de Pronósticos.pdf',
    topics: ['promedios móviles', 'suavizado exponencial', 'MAD', 'estacionalidad'],
    priority: 'alta',
    reason: 'Consolida métodos cuantitativos de pronóstico y las componentes de series de tiempo.',
  },
  {
    id: 'pronosticos-xlsx',
    label: 'Material de estudio/Pronóstico.xlsx',
    path: 'Material de estudio/Pronóstico.xlsx',
    topics: ['ejercicios resueltos', 'MAD', 'promedios móviles', 'índices estacionales'],
    priority: 'alta',
    reason: 'Aporta datasets concretos y formatos de ejercicios muy cercanos a práctica de parcial/final.',
  },
  {
    id: 'redes-modelos',
    label: 'Material de estudio/5. Modelos de redes.pdf',
    path: 'Material de estudio/5. Modelos de redes.pdf',
    topics: ['árbol', 'árbol de expansión mínima', 'Dijkstra'],
    priority: 'alta',
    reason: 'Respalda el bloque de redes y la terminología exacta de la cátedra.',
  },
  {
    id: 'final-2026-simplex',
    label: 'Finales/2026-02-23/WhatsApp Image 2026-02-23 at 20.11.57.jpeg',
    path: 'Finales/2026-02-23/WhatsApp Image 2026-02-23 at 20.11.57.jpeg',
    topics: ['simplex', 'tasa de sustitución', 'índices estacionales'],
    priority: 'alta',
    reason: 'Confirma que el final real pidió una tabla de simplex, un ejercicio de pronóstico y teoría aplicada.',
  },
  {
    id: 'final-2026-pronosticos',
    label: 'Finales/2026-02-23/Resolucion/WhatsApp Image 2026-02-27 at 19.00.19.jpeg',
    path: 'Finales/2026-02-23/Resolucion/WhatsApp Image 2026-02-27 at 19.00.19.jpeg',
    topics: ['pronósticos', 'recta de tendencia', 'lectura del gráfico'],
    priority: 'media',
    reason: 'Aporta una resolución manuscrita del mismo examen y el tipo de lectura gráfica esperada.',
  },
  {
    id: 'final-2026-redes',
    label: 'Finales/2026-02-23/WhatsApp Image 2026-02-23 at 20.11.57 (1).jpeg',
    path: 'Finales/2026-02-23/WhatsApp Image 2026-02-23 at 20.11.57 (1).jpeg',
    topics: ['inventarios', 'árbol de expansión mínima', 'Dijkstra'],
    priority: 'alta',
    reason: 'Prueba que inventarios y redes se toman juntos en el final, con teoría corta asociada.',
  },
  {
    id: 'excluidos-cpm-pert',
    label: 'Material de estudio/CPM.pdf y PERT.pdf',
    path: 'Material de estudio/CPM.pdf | Material de estudio/PERT.pdf',
    topics: ['cpm', 'pert'],
    priority: 'alta',
    reason: 'Se relevaron para descartarlos del alcance, porque Temas de Examen.docx los excluye explícitamente.',
    excluded: true,
  },
]

export const sourceIndex = Object.fromEntries(sourceMap.map((entry) => [entry.id, entry])) as Record<string, SourceMapEntry>
